# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_uname', models.CharField(max_length=100)),
                ('db_upassword', models.CharField(max_length=100)),
            ],
        ),
    ]
